## The Problems worked out here are the problems from the appendix [here](https://moodle.bard.edu/pluginfile.php/139233/course/section/36781/MarslandAppendixA.pdf)

## Problem A1: 
Create an array *a* of size 6 x 4 where every element is a 2

In [2]:
import numpy as np
a = np.full((6,4), 2)
print(a)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


## Problem A2
Create an array *b* of size 6x4 that has 3 on the leading diagonal and 1 everywhere else. 

In [4]:
b = np.full((6,4), 1) #create 6x4 filled with 1's
np.fill_diagonal(b, 3) #adjust leading diagonals to include 3
print(b)

[[3 1 1 1]
 [1 3 1 1]
 [1 1 3 1]
 [1 1 1 3]
 [1 1 1 1]
 [1 1 1 1]]


## Problem A3
Can you multiply these cells together? Why does a\*b work, but not dot(a,b)?

In [8]:
a*b
print(a * b)

[[6 2 2 2]
 [2 6 2 2]
 [2 2 6 2]
 [2 2 2 6]
 [2 2 2 2]
 [2 2 2 2]]


Doing the operation a\*b multiplies the contents of the two vectors. Using the dot function applies matrix multiplication, which only works if a had the same number of columns as b does rows

## Problem A4
Compute `dot(a.transpose(), b)` and `dot(a, b.transpose())`. Why are the results different shapes

In [12]:
print(np.dot(a.transpose(), b))
print(np.dot(a, b.transpose()))

[[16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]]
[[12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]]


Both matrices *a* and *b* are 6 x 4. When *a* is transposed, it becomes a 4 x 6 matrix. The product is now a 4 x 4. 

When *b* is transposed, it becomes a 4 x 6 matrix and *a* stays a 6 x 4. Therefore, the resultant product is a 6 x 6 matrix.

## Problem A5
Write a program that prints some output that you're running

In [13]:
def print_some(thing):
    print(thing)